version: "3.0"

services:
  mongodb:
    container_name: mongodb
    image: mongo:4.0
    volumes:
      - "mongodb_db:/data/db"
      - "mongo_config:/data/configdb"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    restart: always
    ports:
      - "24000:27017"
    deploy:
      resources:
        limits:
          memory: 512M
   
volumes:
  mongodb_db:
  mongo_config: